// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/hearsay/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Hearsay) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *Hearsay) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Hearsay":
		switch fnName {
		case "Build":
			var parent Hearsay
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var arch string
			if inputArgs["arch"] != nil {
				err = json.Unmarshal([]byte(inputArgs["arch"]), &arch)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg arch", err))
				}
			}
			var version string
			if inputArgs["version"] != nil {
				err = json.Unmarshal([]byte(inputArgs["version"]), &version)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg version", err))
				}
			}
			return (*Hearsay).Build(&parent, ctx, arch, version)
		case "Dev":
			var parent Hearsay
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Hearsay).Dev(&parent, ctx)
		case "Image":
			var parent Hearsay
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var arch string
			if inputArgs["arch"] != nil {
				err = json.Unmarshal([]byte(inputArgs["arch"]), &arch)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg arch", err))
				}
			}
			var version string
			if inputArgs["version"] != nil {
				err = json.Unmarshal([]byte(inputArgs["version"]), &version)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg version", err))
				}
			}
			return (*Hearsay).Image(&parent, ctx, arch, version)
		case "ImageCheck":
			var parent Hearsay
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Hearsay).ImageCheck(&parent, ctx)
		case "IntegrationTest":
			var parent Hearsay
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Hearsay).IntegrationTest(&parent, ctx)
		case "Lint":
			var parent Hearsay
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Hearsay).Lint(&parent, ctx)
		case "Migrate":
			var parent Hearsay
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var databaseUrl *dagger.Secret
			if inputArgs["databaseURL"] != nil {
				err = json.Unmarshal([]byte(inputArgs["databaseURL"]), &databaseUrl)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg databaseURL", err))
				}
			}
			var action string
			if inputArgs["action"] != nil {
				err = json.Unmarshal([]byte(inputArgs["action"]), &action)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg action", err))
				}
			}
			var arg string
			if inputArgs["arg"] != nil {
				err = json.Unmarshal([]byte(inputArgs["arg"]), &arg)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg arg", err))
				}
			}
			return (*Hearsay).Migrate(&parent, ctx, databaseUrl, action, arg)
		case "Postgres":
			var parent Hearsay
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Hearsay).Postgres(&parent), nil
		case "Test":
			var parent Hearsay
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Hearsay).Test(&parent, ctx)
		case "TidyCheck":
			var parent Hearsay
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Hearsay).TidyCheck(&parent, ctx)
		case "UnitTest":
			var parent Hearsay
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Hearsay).UnitTest(&parent, ctx)
		case "":
			var parent Hearsay
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ws *dagger.Workspace
			if inputArgs["ws"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ws"]), &ws)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ws", err))
				}
			}
			return New(ws), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithDescription("A Dagger module for Hearsay.\n\nEverything that runs code runs here: lint, the tests, a real Postgres with\npgvector for the ones that need a database, the binary, the container image,\nmigrations and the local dev stack. The gates are `+check` functions, so\n`dagger check` runs them in parallel and reports each one separately, on a\nlaptop and in Dagger Cloud alike.\n").
			WithObject(
				dag.TypeDef().WithObject("Hearsay", dagger.TypeDefWithObjectOpts{Description: "Hearsay is the module's entry point.", SourceMap: dag.SourceMap("main.go", 62, 6)}).
					WithFunction(
						dag.Function("Build",
							dag.TypeDef().WithObject("File")).
							WithDescription("Build compiles the hearsay binary for Linux.").
							WithSourceMap(dag.SourceMap("main.go", 212, 1)).
							WithArg("arch", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Target architecture (amd64, arm64). Defaults to the engine's own.", SourceMap: dag.SourceMap("main.go", 216, 2)}).
							WithArg("version", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Version to stamp into the binary. Defaults to what internal/version works\nout for itself.", SourceMap: dag.SourceMap("main.go", 221, 2)})).
					WithFunction(
						dag.Function("Dev",
							dag.TypeDef().WithObject("Service")).
							WithDescription("Dev runs the local stack: Postgres with pgvector, and all four services in one\nprocess (ADR-0003's `hearsay all`).\n\n\tdagger up dev\n\nThere is no file watcher. Restarting is the reload: stop the command and run\nit again, and the rebuild is a cached one.").
							WithSourceMap(dag.SourceMap("main.go", 344, 1)).
							WithUp()).
					WithFunction(
						dag.Function("Image",
							dag.TypeDef().WithObject("Container")).
							WithDescription("Image builds the container image hearsay ships in. One image runs all four\nservices; the subcommand is the argument (ADR-0003).").
							WithSourceMap(dag.SourceMap("main.go", 249, 1)).
							WithArg("arch", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Target architecture (amd64, arm64). Defaults to the engine's own.", SourceMap: dag.SourceMap("main.go", 253, 2)}).
							WithArg("version", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Version to stamp into the binary.", SourceMap: dag.SourceMap("main.go", 257, 2)})).
					WithFunction(
						dag.Function("ImageCheck",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("ImageCheck builds the container image, so that an image that no longer builds\nfails here rather than at a release.").
							WithSourceMap(dag.SourceMap("main.go", 190, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("IntegrationTest",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("IntegrationTest runs the tests tagged `integration` against a real Postgres\nwith pgvector.").
							WithSourceMap(dag.SourceMap("main.go", 145, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("Lint",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Lint the module: go vet, golangci-lint and the formatter check.").
							WithSourceMap(dag.SourceMap("main.go", 84, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("Migrate",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Migrate applies the schema migrations to a database (ADR-0006).\n\n\tdagger api call hearsay migrate --database-url=env:HEARSAY_DATABASE_URL\n\nADR-0006 spells that `dagger call migrate`, which was the command in Dagger\n0.21. The function is the one the ADR names; only the CLI verb moved.\n\nEvery action exits non-zero with \"not implemented yet\" until goose and the\nembedded migrations land with the L0 store.").
							WithSourceMap(dag.SourceMap("main.go", 301, 1)).
							WithArg("databaseURL", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{Description: "Postgres connection URL, for example\npostgres://hearsay:hearsay@localhost:5432/hearsay.", SourceMap: dag.SourceMap("main.go", 304, 2)}).
							WithArg("action", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "up, status, up-to or down.", SourceMap: dag.SourceMap("main.go", 309, 2), DefaultValue: dagger.JSON("\"up\"")}).
							WithArg("arg", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "The target version, for up-to.", SourceMap: dag.SourceMap("main.go", 313, 2)})).
					WithFunction(
						dag.Function("Postgres",
							dag.TypeDef().WithObject("Service")).
							WithDescription("Postgres is the throwaway Postgres with pgvector that the integration test and\nthe dev stack run against.").
							WithSourceMap(dag.SourceMap("main.go", 282, 1))).
					WithFunction(
						dag.Function("Test",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Test runs the whole suite: the unit tests, and the integration tests against a\nreal Postgres with pgvector. Both are checks in their own right, so\n`dagger check` runs them in parallel; this is for asking for exactly the two.").
							WithSourceMap(dag.SourceMap("main.go", 204, 1))).
					WithFunction(
						dag.Function("TidyCheck",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("TidyCheck fails if `go mod tidy` would change go.mod or go.sum.").
							WithSourceMap(dag.SourceMap("main.go", 108, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("UnitTest",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("UnitTest runs the tests that need nothing but the module.").
							WithSourceMap(dag.SourceMap("main.go", 130, 1)).
							WithCheck()).
					WithField("Source", dag.TypeDef().WithObject("Directory"), dagger.TypeDefWithFieldOpts{Description: "The repository, read from the workspace.", SourceMap: dag.SourceMap("main.go", 64, 2)}).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("Hearsay")).
							WithSourceMap(dag.SourceMap("main.go", 67, 1)).
							WithArg("ws", dag.TypeDef().WithObject("Workspace"), dagger.FunctionWithArgOpts{Description: "The current workspace, auto-populated by Dagger.", SourceMap: dag.SourceMap("main.go", 69, 2)}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
