// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Hearsay is the module's entry point.
type Hearsay struct { // hearsay (../../../:0:0)
	query *querybuilder.Selection

	id              *ID
	imageCheck      *Void
	integrationTest *Void
	lint            *Void
	migrate         *string
	test            *Void
	tidyCheck       *Void
	unitTest        *Void
}

func (r *Hearsay) WithGraphQLQuery(q *querybuilder.Selection) *Hearsay {
	return &Hearsay{
		query: q,
	}
}

// HearsayBuildOpts contains options for Hearsay.Build
type HearsayBuildOpts struct {
	// Target architecture (amd64, arm64). Defaults to the engine's own.
	Arch string
	// Version to stamp into the binary. Defaults to what internal/version works
	// out for itself.
	Version string
}

// Build compiles the hearsay binary for Linux.
func (r *Hearsay) Build(opts ...HearsayBuildOpts) *File {
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return &File{
		query: q,
	}
}

// Dev runs the local stack: Postgres with pgvector, and all four services in one
// process (ADR-0003's `hearsay all`).
//
//	dagger up dev
//
// There is no file watcher. Restarting is the reload: stop the command and run
// it again, and the rebuild is a cached one.
func (r *Hearsay) Dev() *Service {
	q := r.query.Select("dev")

	return &Service{
		query: q,
	}
}

// A unique identifier for this Hearsay.
func (r *Hearsay) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Hearsay) XXX_GraphQLType() string {
	return "Hearsay"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Hearsay) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Hearsay) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Hearsay) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Hearsay) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Hearsay{query: selectNode(dag.query, id, "Hearsay")}
	return nil
}

// HearsayImageOpts contains options for Hearsay.Image
type HearsayImageOpts struct {
	// Target architecture (amd64, arm64). Defaults to the engine's own.
	Arch string
	// Version to stamp into the binary.
	Version string
}

// Image builds the container image hearsay ships in. One image runs all four
// services; the subcommand is the argument (ADR-0003).
func (r *Hearsay) Image(opts ...HearsayImageOpts) *Container {
	q := r.query.Select("image")
	for i := len(opts) - 1; i >= 0; i-- {
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return &Container{
		query: q,
	}
}

// ImageCheck builds the container image, so that an image that no longer builds
// fails here rather than at a release.
func (r *Hearsay) ImageCheck(ctx context.Context) error {
	if r.imageCheck != nil {
		return nil
	}
	q := r.query.Select("imageCheck")

	return q.Execute(ctx)
}

// IntegrationTest runs the tests tagged `integration` against a real Postgres
// with pgvector.
func (r *Hearsay) IntegrationTest(ctx context.Context) error {
	if r.integrationTest != nil {
		return nil
	}
	q := r.query.Select("integrationTest")

	return q.Execute(ctx)
}

// Lint the module: go vet, golangci-lint and the formatter check.
func (r *Hearsay) Lint(ctx context.Context) error {
	if r.lint != nil {
		return nil
	}
	q := r.query.Select("lint")

	return q.Execute(ctx)
}

// HearsayMigrateOpts contains options for Hearsay.Migrate
type HearsayMigrateOpts struct {
	// up, status, up-to or down.
	//
	// Default: "up"
	Action string
	// The target version, for up-to.
	Arg string
}

// Migrate applies the schema migrations to a database (ADR-0006).
//
//	dagger api call hearsay migrate --database-url=env:HEARSAY_DATABASE_URL
//
// ADR-0006 spells that `dagger call migrate`, which was the command in Dagger
// 0.21. The function is the one the ADR names; only the CLI verb moved.
//
// Every action exits non-zero with "not implemented yet" until goose and the
// embedded migrations land with the L0 store.
func (r *Hearsay) Migrate(ctx context.Context, databaseUrl *Secret, opts ...HearsayMigrateOpts) (string, error) {
	assertNotNil("databaseUrl", databaseUrl)
	if r.migrate != nil {
		return *r.migrate, nil
	}
	q := r.query.Select("migrate")
	for i := len(opts) - 1; i >= 0; i-- {
		// `action` optional argument
		if !querybuilder.IsZeroValue(opts[i].Action) {
			q = q.Arg("action", opts[i].Action)
		}
		// `arg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arg) {
			q = q.Arg("arg", opts[i].Arg)
		}
	}
	q = q.Arg("databaseUrl", databaseUrl)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Postgres is the throwaway Postgres with pgvector that the integration test and
// the dev stack run against.
func (r *Hearsay) Postgres() *Service {
	q := r.query.Select("postgres")

	return &Service{
		query: q,
	}
}

// The repository, read from the workspace.
func (r *Hearsay) Source() *Directory {
	q := r.query.Select("source")

	return &Directory{
		query: q,
	}
}

// Test runs the whole suite: the unit tests, and the integration tests against a
// real Postgres with pgvector. Both are checks in their own right, so
// `dagger check` runs them in parallel; this is for asking for exactly the two.
func (r *Hearsay) Test(ctx context.Context) error {
	if r.test != nil {
		return nil
	}
	q := r.query.Select("test")

	return q.Execute(ctx)
}

// TidyCheck fails if `go mod tidy` would change go.mod or go.sum.
func (r *Hearsay) TidyCheck(ctx context.Context) error {
	if r.tidyCheck != nil {
		return nil
	}
	q := r.query.Select("tidyCheck")

	return q.Execute(ctx)
}

// UnitTest runs the tests that need nothing but the module.
func (r *Hearsay) UnitTest(ctx context.Context) error {
	if r.unitTest != nil {
		return nil
	}
	q := r.query.Select("unitTest")

	return q.Execute(ctx)
}

func (r *Query) Hearsay(ws *Workspace) *Hearsay { // hearsay (../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("hearsay")
	q = q.Arg("ws", ws)

	return &Hearsay{
		query: q,
	}
}
